### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by timglabisch** [zzo/JUTE#1]
i cant install jute using npm, i think the reason is the bad ssl certification. have a look at:

npm verb mkdir (expected) error ENOENT, No such file or directory '/tmp/npm-1313140401679/1313140401680-0.394858424551785'
npm verb mkdir done: /tmp/npm-1313140401679/1313140401680-0.394858424551785 755
npm info fetch https://registry.npmjs.org/jute/-/jute-0.0.10.tgz
npm verb fetch to /tmp/npm-1313140401679/1313140401680-0.394858424551785/tmp.tgz

if i open the url https://registry.npmjs.org/jute/-/jute-0.0.10.tgz in a browser i get an error that the ssl certification isn't trusted.

**Comment by timglabisch** [comment]
npm ERR! failed to fetch https://registry.npmjs.org/jute/-/jute-0.0.10.tgz
npm ERR! Error: socket hang up
npm ERR!     at Socket.<anonymous> (http2.js:1146:25)
npm ERR!     at Socket.emit (events.js:67:17)
npm ERR!     at Array.0 (net_legacy.js:851:12)
npm ERR!     at EventEmitter._tickCallback (node.js:197:26)
npm ERR! Report this _entire_ log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com
npm ERR! 
npm ERR! System Linux 2.6.32-28-server
npm ERR! command "node" "/usr/local/bin/npm" "install" "jute" "-g" "--verbose"
npm ERR! cwd /home/any/Desktop/node/node
npm ERR! node -v v0.5.4
npm ERR! npm -v 1.0.24
npm verb exit [ 1, true ]
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/any/Desktop/node/node/npm-debug.log
npm not ok

**Comment by zzo** [comment]
Hey Tim - apparently npm is NOT compatible/working with node .5.4 - do you have .4.10 lying around to use??

Here is the issue:

https://github.com/isaacs/npm/issues/1218

**Comment by isaacs** [comment]
Please use node 0.4.10 for now.
